# Site settings
title: לפני המבול
description: > # this means to ignore newlines until "baseurl:"
   על הכיבוש, על הדיכוי, ועל החופש שהולך ונעלם
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
paginate: 5 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
